# Generated by Django 3.1.7 on 2023-02-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2001-11-02'),
            preserve_default=False,
        ),
    ]
